<?php
// module/Album/view/album/album/add.phtml:

$title = 'Create albums';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<div class="row">
    <article class="col-md-5">
        <?php if ($this->error): ?>
            <p class="error">
                There were one or more issues with your submission.
                Please correct them as
                indicated below.
            </p>
        <?php endif ?>
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('album', array('action' => 'add')));
        $form->setAttribute('method', 'post');
        $form->prepare();

        echo $this->form()->openTag($form);
//        echo $this->formHidden($form->get('id'));       
        ?>
        <div class="form-group">
            <label>
                <?php echo $this->formLabel($form->get('title')); ?>
            </label>

            <?php
            echo $this->formElement($form->get('title'));
            echo $this->formElementErrors($form->get('title'));
            ?>

        </div>
        <div class="form-group">
            <label>
                <?php echo $this->formLabel($form->get('artist')); ?>
            </label>
            <?php
            echo $this->formElement($form->get('artist'));
            echo $this->formElementErrors($form->get('artist'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </article>
</div>
